### ISSUE TITLE
Pipeline in kfpv2 is failling at first step with a ResourceNotFoundError error

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#147]
When running a pipeline using kfpv2 code, the following error is shown in the first step:

```
F0531 13:38:27.378860 14 main.go:49] failed to execute component: failed to create task: rpc error: code = NotFound desc = Failed to create a new task: Failed to create a task for run 92ab9e7f-8e23-41e1-a5f8-3f4899bdc763: Failed to fetch run 92ab9e7f-8e23-41e1-a5f8-3f4899bdc763: ResourceNotFoundError: Run 92ab9e7f-8e23-41e1-a5f8-3f4899bdc763 not found 
```

Which blocks the pipeline to run the next steps.

Slack thread to discuss this issue with ktp-tekton team: https://redhat-external.slack.com/archives/C057CFAE10A/p1685540441098889

**Comment by rimolive** [comment]
A workaround to supress that error is disable cache in the pipeline (it is set to true by default, not sure if there's a way to disable it through SDK), because some endpoints are "hard-coded". They have default values but always consider that kfpv2 is deployed on kubeflow namespace.

However, even with cache disabled, we get errors that the PipelineRun cannot be found. There might be other hard-coded locations in the code that prevents the pipeline to run successfuly
