### ISSUE TITLE
Write Unit Tests

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#162]
Currently the DSPO 'unit' tests are actually integration/api blackbox tests.  Write a suite of smaller whitebox/unit tests to verify basic code functionality. 

Acceptance Criteria: 
Set up unit test framework with ~20% min code coverage (feel free to over achieve).

**Comment by HumairAK** [comment]
We should also rename the prow jobs because currently they show up as prow/unit, and these are more functional/api tests for the dspo, and that's misleading, I think they are named here: https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/data-science-pipelines-operator/opendatahub-io-data-science-pipelines-operator-main.yaml#L35
