### ISSUE TITLE
E2E Pipeline sample for V2

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#175]
Similar to #174, but write the same pipeline in v2. This pipeline will be utilized to evaluate v2 readiness on OCP for ODH, and adoption in dspo.

**Comment by rimolive** [comment]
Ideally, iris pipeline v2 could be enhanced to support multiple visualization metrics and thus bringing all the artifacts that is possible to use in a KFPv2 pipeline. Because of [kubeflow/pipelines#10208](https://github.com/kubeflow/pipelines/issues/10208), we cannot provide an example of a ROC Curve. We need to wait until [kubeflow/pipelines#10209](https://github.com/kubeflow/pipelines/pull/10209) is merged, so we can rebase in `kfp-tekton` and `data-science-pipeline` repos, as well as update pip channels to support this change.

**Comment by rimolive** [comment]
Although the ROC Curve example would be beneficial, it will take longer to have a fix. Let's for now keep the current iris-pipeline example as the E2E sample while working on other examples as described in #455
