### ISSUE TITLE
[Spike] Investigate noobaa as a possible out of the box s3 storage solution

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#179]
In the past the core team has investigated nooba and found it to be an expensive addon as a side service to DSP, this was a long time ago, we should re visit those findings, and confirm whether anything has changed since that that would allow for a lighter weight deployment of nooba alongside dsp, for an out of box solution.

@guimou is suggested as a good contact regarding this issue.

**Comment by HumairAK** [comment]
As part of this spike, we should also look into other potential popular light weight open source solutions if they exist.

**Comment by gmfrasca** [comment]
Just adding more context to this SPIKE, but we (the Data Science Pipelines team at Red Hat) have investigated and addressed the concern of S3 storage options several times throughout the initial development and offering of this component, and have concluded that the only viable option at present time is to have users provide their own S3 storage.

With that said, we identify the benefit of ease-of-use that comes with having an operator-managed lightweight S3 option.  However, we also realize any additional movement in this area will need to come from a broader scope, ie an ODH Organizational decision rather than us as an individual component.  Should such a decision and offering become available, we will readdress and work to implement this as an option for Data Science Pipelines
