### ISSUE TITLE
Create PoC that supports DSPAs using different Execution Engines simulatneously

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#444]

**Comment by gregsheremeta** [comment]
I would feel better if we didn't commit this to our main repo due to [YAGNI](https://martinfowler.com/bliki/Yagni.html).

**Comment by HumairAK** [comment]
I think we should keep the API fields there and just say we dont' support the following combinations: 

1. "V1 with argo" 
2. "V2 with tekton" 

While (1) is never going to happen, (2) is something I can see is a bit more unclear, and having the api designed in such a way that allows for this is fine imo. But let's not add the manifests for the tekton implementation (assuming argo is a sure thing, otherwise flip tekton w/ argo).

**Comment by DharmitD** [comment]
Multi-engine PoC lgtm, provided we plan on handling the engine/version combinations correctly.
I would suggest we merge the PoC and not let it sit, considering we might utilize most of it if we choose argo anyway, and to avoid a messy rebase in the future.
